<?php

namespace Modules\Settings\Filament\Resources\Setting\Tables;

use Filament\Actions\BulkActionGroup;
use Filament\Actions\DeleteBulkAction;
use Filament\Actions\EditAction;
use Filament\Tables\Columns\IconColumn;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Table;

class SettingsTable
{
    public static function configure(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('logo')
                    ->searchable(),
                TextColumn::make('brand_name')
                    ->searchable(),
                TextColumn::make('tagline')
                    ->searchable(),
                TextColumn::make('admin_email')
                    ->searchable(),
                TextColumn::make('default_currency')
                    ->numeric()
                    ->sortable(),
                IconColumn::make('mpgs_enable')
                    ->boolean(),
                TextColumn::make('mpgs_merchant_id')
                    ->searchable(),
                TextColumn::make('mpgs_username')
                    ->searchable(),
                TextColumn::make('mpgs_api_url')
                    ->searchable(),
                TextColumn::make('mpgs_version')
                    ->searchable(),
                TextColumn::make('mpgs_dashboard_link')
                    ->searchable(),
                IconColumn::make('live_mpgs_enable')
                    ->boolean(),
                TextColumn::make('live_mpgs_merchant_id')
                    ->searchable(),
                TextColumn::make('live_mpgs_username')
                    ->searchable(),
                TextColumn::make('live_mpgs_api_url')
                    ->searchable(),
                TextColumn::make('live_mpgs_version')
                    ->searchable(),
                IconColumn::make('paymob_enable')
                    ->boolean(),
                TextColumn::make('paymob_public_key')
                    ->searchable(),
                TextColumn::make('paymob_secret_key')
                    ->searchable(),
                TextColumn::make('paymob_hmac')
                    ->searchable(),
                TextColumn::make('paymob_mobile_wallet_integration_id')
                    ->searchable(),
                TextColumn::make('paymob_valu_integration_id')
                    ->searchable(),
                IconColumn::make('smtp_enable')
                    ->boolean(),
                TextColumn::make('smtp_host')
                    ->searchable(),
                TextColumn::make('smtp_port')
                    ->searchable(),
                TextColumn::make('smtp_encryption')
                    ->searchable(),
                TextColumn::make('smtp_username')
                    ->searchable(),
                TextColumn::make('smtp_mail_from')
                    ->searchable(),
                IconColumn::make('create_send_enable')
                    ->boolean(),
                TextColumn::make('create_send_api_key')
                    ->searchable(),
                TextColumn::make('create_send_list_id')
                    ->searchable(),
                TextColumn::make('create_send_template_id')
                    ->searchable(),
                TextColumn::make('create_send_client_id')
                    ->searchable(),
                TextColumn::make('create_send_from_email')
                    ->searchable(),
                TextColumn::make('create_send_replay_to')
                    ->searchable(),
                IconColumn::make('send_grid_enable')
                    ->boolean(),
                TextColumn::make('send_grid_host')
                    ->searchable(),
                TextColumn::make('send_grid_port')
                    ->searchable(),
                TextColumn::make('send_grid_username')
                    ->searchable(),
                TextColumn::make('send_grid_mail_from')
                    ->searchable(),
                TextColumn::make('send_grid_encryption')
                    ->searchable(),
                IconColumn::make('whatsapp_is_enabled')
                    ->boolean(),
                TextColumn::make('whatsapp_from_number')
                    ->searchable(),
                IconColumn::make('apply_tax')
                    ->boolean(),
                TextColumn::make('tax_rate')
                    ->numeric()
                    ->sortable(),
                IconColumn::make('is_trello_active')
                    ->boolean(),
                TextColumn::make('trello_board_id')
                    ->searchable(),
                TextColumn::make('email_primary_color')
                    ->searchable(),
                TextColumn::make('email_secondary_color')
                    ->searchable(),
                TextColumn::make('email_background_color')
                    ->searchable(),
                TextColumn::make('email_text_color')
                    ->searchable(),
                TextColumn::make('email_button_color')
                    ->searchable(),
                TextColumn::make('email_button_text_color')
                    ->searchable(),
                TextColumn::make('email_logo')
                    ->searchable(),
                TextColumn::make('processing_order_list_id')
                    ->searchable(),
                TextColumn::make('shipped_order_list_id')
                    ->searchable(),
                TextColumn::make('completed_order_list_id')
                    ->searchable(),
                TextColumn::make('cancelled_order_list_id')
                    ->searchable(),
                TextColumn::make('subscription_list_id')
                    ->searchable(),
                TextColumn::make('contact_us_list_id')
                    ->searchable(),
                TextColumn::make('working_hour_start')
                    ->searchable(),
                TextColumn::make('working_hour_end')
                    ->searchable(),
                TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                //
            ])
            ->recordActions([
                EditAction::make(),
            ])
            ->toolbarActions([
                BulkActionGroup::make([
                    DeleteBulkAction::make(),
                ]),
            ]);
    }
}
